/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'FanChain_IconFont\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-SEND': '&#xe99f;',
		'icon-INSIGHTS': '&#xe99c;',
		'icon-POPULAR': '&#xe99d;',
		'icon-LIVE': '&#xe99e;',
		'icon-CHOOSE': '&#xe99b;',
		'icon-CASTSYNC': '&#xe999;',
		'icon-CASTRDNA': '&#xe99a;',
		'icon-BLOCK': '&#xe998;',
		'icon-VERSUS': '&#xe91f;',
		'icon-FANBET': '&#xe96f;',
		'icon-BETS_COMPLETE': '&#xe995;',
		'icon-BETS_CURRENT': '&#xe996;',
		'icon-LEAVE': '&#xe997;',
		'icon-BADMINTON': '&#xe98e;',
		'icon-BOWLING': '&#xe98f;',
		'icon-RACING': '&#xe990;',
		'icon-FIGHTING': '&#xe991;',
		'icon-BILLIARDS': '&#xe992;',
		'icon-GOLF': '&#xe993;',
		'icon-BOXING': '&#xe98a;',
		'icon-HOCKEY': '&#xe97f;',
		'icon-BASEBALL': '&#xe980;',
		'icon-VOLLEYBALL': '&#xe97e;',
		'icon-TENNIS': '&#xe97c;',
		'icon-SOCCER': '&#xe982;',
		'icon-BASKETBALL': '&#xe981;',
		'icon-FOOTBALL': '&#xe97d;',
		'icon-ESPORTS': '&#xe97b;',
		'icon-KEYBOARD_SHOW': '&#xe994;',
		'icon-KEYBOARD_HIDE': '&#xe98b;',
		'icon-CART_ADD': '&#xe903;',
		'icon-CART': '&#xe985;',
		'icon-DASHBOARD': '&#xe957;',
		'icon-GLOBAL': '&#xe96d;',
		'icon-ACHIEVEMENTS': '&#xe971;',
		'icon-HIGHLIGHTS': '&#xe972;',
		'icon-FAV_FILLED': '&#xe973;',
		'icon-FAV_EMPTY': '&#xe975;',
		'icon-STAR_RATE': '&#xe986;',
		'icon-LIST_VIEW': '&#xe91b;',
		'icon-FANZ_CIRCLE': '&#xe902;',
		'icon-FANZ': '&#xe96b;',
		'icon-FANWALLET': '&#xe947;',
		'icon-FANPAY': '&#xe989;',
		'icon-FANPRIZES': '&#xe984;',
		'icon-FANEXCHANGE': '&#xe988;',
		'icon-MINT': '&#xe976;',
		'icon-COLLAPSE': '&#xe977;',
		'icon-EXPAND': '&#xe978;',
		'icon-DONUT': '&#xe979;',
		'icon-SHIPPING': '&#xe983;',
		'icon-SPOTLIGHT': '&#xe970;',
		'icon-SCAN_QR': '&#xe96e;',
		'icon-QR': '&#xe954;',
		'icon-EVENT': '&#xe96a;',
		'icon-LOCK': '&#xe929;',
		'icon-UNLOCK': '&#xe967;',
		'icon-PRESENTATION': '&#xe968;',
		'icon-TERMS': '&#xe969;',
		'icon-DOCUMENT': '&#xe965;',
		'icon-YOUTUBE': '&#xe958;',
		'icon-TELEGRAM': '&#xe95d;',
		'icon-MAGIC': '&#xe95e;',
		'icon-VISIBILITY': '&#xe95f;',
		'icon-MAINTAIN': '&#xe963;',
		'icon-WALLET': '&#xe953;',
		'icon-OFFERS': '&#xe955;',
		'icon-INSTANT': '&#xe956;',
		'icon-PERSONALIZE': '&#xe950;',
		'icon-TRADE': '&#xe952;',
		'icon-REPLAY': '&#xe933;',
		'icon-HISTORY': '&#xe97a;',
		'icon-TICKER': '&#xe951;',
		'icon-COIN': '&#xe94b;',
		'icon-MONEY': '&#xe94c;',
		'icon-TIP': '&#xe94d;',
		'icon-TIP_LEADER': '&#xe94e;',
		'icon-EMBED': '&#xe948;',
		'icon-OBS': '&#xe949;',
		'icon-DOWNLOAD': '&#xe94a;',
		'icon-SHARE': '&#xe92b;',
		'icon-SHARE_ARROW': '&#xe942;',
		'icon-FILTER': '&#xe960;',
		'icon-GENDER_MALE': '&#xe93f;',
		'icon-GENDER_FEMALE': '&#xe93e;',
		'icon-GENDER_ALL': '&#xe93d;',
		'icon-GENDER_NEUTRAL': '&#xe961;',
		'icon-ADD_A_PHOTO': '&#xe904;',
		'icon-MIC': '&#xe906;',
		'icon-LEGAL': '&#xe907;',
		'icon-MENU': '&#xe909;',
		'icon-SEE_MORE': '&#xe92a;',
		'icon-COMPLETE': '&#xe905;',
		'icon-LINK': '&#xe90a;',
		'icon-TEXTSMS': '&#xe90b;',
		'icon-DELETE': '&#xe910;',
		'icon-EMAIL': '&#xe90c;',
		'icon-LAPTOP': '&#xe90d;',
		'icon-MOBILE': '&#xe90f;',
		'icon-NOTIFICATIONS': '&#xe913;',
		'icon-ADD': '&#xe916;',
		'icon-CLOSE': '&#xe92d;',
		'icon-UP': '&#xe94f;',
		'icon-BACK': '&#xe917;',
		'icon-HIDE': '&#xe900;',
		'icon-CONTINUE': '&#xe918;',
		'icon-COMMENT': '&#xe919;',
		'icon-LEADERBOARD': '&#xe912;',
		'icon-PHONE': '&#xe91a;',
		'icon-DISCOVER': '&#xe914;',
		'icon-HELP': '&#xe911;',
		'icon-INFO_CIRCLE': '&#xe93c;',
		'icon-SETTINGS': '&#xe915;',
		'icon-GOOGLE_AUTH': '&#xe98c;',
		'icon-GOOGLE': '&#xe98d;',
		'icon-FACEBOOK': '&#xe91e;',
		'icon-TWITTER': '&#xe91c;',
		'icon-INSTAGRAM': '&#xe908;',
		'icon-LINKEDIN': '&#xe95a;',
		'icon-REDDIT': '&#xe95c;',
		'icon-MEDIUM': '&#xe95b;',
		'icon-APPLE': '&#xe91d;',
		'icon-GITHUB': '&#xe959;',
		'icon-ANDROID': '&#xe966;',
		'icon-BITCOIN_TALK': '&#xe96c;',
		'icon-HOME': '&#xe920;',
		'icon-FLAG': '&#xe927;',
		'icon-TIX': '&#xe92c;',
		'icon-TIX_ADD': '&#xe974;',
		'icon-STATS': '&#xe923;',
		'icon-TV': '&#xe924;',
		'icon-DIGITAL_GIFT': '&#xe926;',
		'icon-HEADSET': '&#xe928;',
		'icon-CHAT': '&#xe925;',
		'icon-FLIP_CAM': '&#xe92e;',
		'icon-MUTE_MIC': '&#xe92f;',
		'icon-SOUND_UP': '&#xe945;',
		'icon-SOUND_DOWN': '&#xe943;',
		'icon-SOUND_MUTE': '&#xe944;',
		'icon-WIFI': '&#xe934;',
		'icon-EDIT': '&#xe935;',
		'icon-PROFILE': '&#xe932;',
		'icon-CONTACTS': '&#xe941;',
		'icon-VIEWER': '&#xe936;',
		'icon-ACCOUNT_ALERT': '&#xe964;',
		'icon-UNFOLLOW': '&#xe922;',
		'icon-FOLLOW': '&#xe921;',
		'icon-NEW_FANS': '&#xe90e;',
		'icon-COMMUNITY': '&#xe987;',
		'icon-END': '&#xe938;',
		'icon-PLAY_ARROW': '&#xe937;',
		'icon-PLAY_CIRCLE': '&#xe93b;',
		'icon-PAUSE': '&#xe931;',
		'icon-PAUSE_CIRCLE': '&#xe940;',
		'icon-GO_LIVE': '&#xe939;',
		'icon-PIP': '&#xe901;',
		'icon-PIP_MID': '&#xe93a;',
		'icon-PIP_FAT': '&#xe946;',
		'icon-SPACER': '&#xe930;',
		'icon-SPORTSCASTR': '&#xe962;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
